# Generated by Django 4.2.3 on 2023-07-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='برند')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برند های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تگ')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان دسته بندی')),
                ('url_title', models.CharField(max_length=300, verbose_name='عنوان در url')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی های محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان محصول')),
                ('short_description', models.CharField(max_length=200, verbose_name='توضیحات کوتاه محصول')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات اصلی محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('color', models.CharField(max_length=20, verbose_name='رنگ محصول')),
                ('image', models.ImageField(upload_to='images/product-image', verbose_name='تصویر اصلی محصول')),
                ('slug', models.CharField(blank=True, max_length=300, verbose_name='اسلاگ')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='دسته بندی محصول')),
                ('tags', models.ManyToManyField(to='product_module.producttags', verbose_name='تگ های محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
