# Generated by Django 4.2.3 on 2023-08-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productcommentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentmodel',
            name='comment',
            field=models.TextField(verbose_name='متن کامنت'),
        ),
    ]
