# Generated by Django 4.2.3 on 2023-08-24 11:35
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_productcommentmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now(), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
