# Generated by Django 4.2.3 on 2023-08-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productcommentmodel_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcommentmodel',
            name='create_date',
        ),
    ]
