# Generated by Django 4.2.3 on 2023-08-24 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_productcommentmodel_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 24, 15, 10, 9, 406036), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
