# Generated by Django 4.2.3 on 2023-08-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_productcommentmodel_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول'),
            preserve_default=False,
        ),
    ]
