# Generated by Django 4.2.3 on 2023-08-24 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0010_productcommentmodel_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommentLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productcommentmodel', verbose_name='کامنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک کامنت محصول',
                'verbose_name_plural': 'لایک های کامنت های محصولات',
            },
        ),
    ]
