# Generated by Django 4.2.3 on 2023-08-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_productcommentlikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/category-image', verbose_name='تصویر دسته بندی'),
        ),
    ]
