# Generated by Django 4.2.3 on 2023-08-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'جزویات سبد خرید', 'verbose_name_plural': 'جزئیات سبد های خرید کاربران'},
        ),
    ]
