# Generated by Django 4.2.3 on 2023-08-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_alter_orderitems_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='prodcut',
            new_name='product',
        ),
    ]
