# Generated by Django 4.2.3 on 2023-08-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='نام سایت')),
                ('domin_name', models.CharField(max_length=50, verbose_name='دامنه سایت')),
                ('addres', models.CharField(max_length=100, verbose_name='آدرس')),
                ('phone', models.IntegerField(verbose_name='تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('telegram', models.CharField(max_length=50, verbose_name='تلگرام')),
                ('twitter', models.CharField(max_length=50, verbose_name='توئیتر')),
                ('instagram', models.CharField(max_length=50, verbose_name='اینستاگرام')),
                ('facebook', models.CharField(max_length=50, verbose_name='فیسبوک')),
                ('pinteres', models.CharField(max_length=50, verbose_name='پینترست')),
                ('rules', models.TextField(max_length=50, verbose_name='قوانین')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'لیست تنظیمات سایت',
            },
        ),
    ]
