# Generated by Django 4.2.3 on 2023-08-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemodel',
            old_name='addres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='domin_name',
            new_name='domain_name',
        ),
    ]
