# Generated by Django 4.2.3 on 2023-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_rename_addres_sitemodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='copy_right',
            field=models.CharField(default='سجاد احمدی زاد', max_length=50, verbose_name='متن کپی رایت'),
            preserve_default=False,
        ),
    ]
