# Generated by Django 4.2.3 on 2023-08-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='متن تماس باما')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('answer', models.TextField(verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'فرم تماس باما',
                'verbose_name_plural': 'فرم های تماس باما',
            },
        ),
    ]
