# Generated by Django 4.2.3 on 2023-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='B8FkPsKEb4iRw6mTJIiD', max_length=20, unique=True, verbose_name='یوزرنیم'),
        ),
    ]
