# Generated by Django 4.2.3 on 2023-07-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(max_length=100, verbose_name='کد فعالسازی ایمیل'),
        ),
    ]
