# Generated by Django 4.2.3 on 2023-08-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='email',
            field=models.CharField(default='a@gmail.com', max_length=50, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
