# Generated by Django 4.2.3 on 2023-08-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_remove_passwordresettoken_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/user-profiles', verbose_name='تصویر آواتار'),
        ),
    ]
