# Generated by Django 4.2.3 on 2023-08-27 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_user_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.AddField(
            model_name='user',
            name='last_reset_password_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 27, 4, 9, 18, 934654), verbose_name='زمان دریافت آخرین ایمیل بازیابی کلمه عبور'),
            preserve_default=False,
        ),
    ]
