# Generated by Django 4.2.3 on 2023-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_delete_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_reset_password_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان دریافت آخرین ایمیل بازیابی کلمه عبور'),
        ),
    ]
